--CRIANDO AS TABELAS

CREATE TABLE MATERIA_PRIMA (
 COD_MATERIA_PRIMA NUMBER CONSTRAINT PK_MATPRI_CODMATPRI PRIMARY KEY,
 MATERIA_PRIMA VARCHAR2(20) CONSTRAINT UK_MATPRI_MATPRI UNIQUE
);

CREATE TABLE CATEGORIA (
 COD_CATEGORIA NUMBER CONSTRAINT PK_CAT_CODCAT PRIMARY KEY,
 CATEGORIA VARCHAR2(20) CONSTRAINT UK_CAT_CAT UNIQUE CONSTRAINT CK_CAT_CAT CHECK(CATEGORIA IN('DOCE','BEBIDA','CONGELADO'))
);

CREATE TABLE PRODUTO (
 COD_PRODUTO NUMBER CONSTRAINT PK_PRO_CODPRO PRIMARY KEY,
 COD_CATEGORIA NUMBER CONSTRAINT FK_PRODUTO_CATEGORIA REFERENCES CATEGORIA(COD_CATEGORIA),
 PRODUTO VARCHAR2(20) CONSTRAINT UK_PRO_PRO UNIQUE
);

CREATE TABLE ITEM_PRODUTO (
 COD_PRODUTO NUMBER,
 COD_MATERIA_PRIMA NUMBER,
 QUANTIDADE NUMBER CONSTRAINT NN_ITEPRO_QDE NOT NULL,
 CONSTRAINT PK_ITEPRO_CODPRO_COD_MAT PRIMARY KEY (COD_PRODUTO, COD_MATERIA_PRIMA),
 CONSTRAINT FK_ITEPRO_CODPRO FOREIGN KEY (COD_PRODUTO) REFERENCES PRODUTO(COD_PRODUTO),
 CONSTRAINT FK_ITEPRO_CODMATPRI FOREIGN KEY (COD_MATERIA_PRIMA) REFERENCES MATERIA_PRIMA(COD_MATERIA_PRIMA)
);

--ALTERAÇÃO DAS TABELAS E CAMPOS

ALTER TABLE ITEM_PRODUTO
ADD TIPO_MEDIDA VARCHAR2(30);

--MESMA ALTERAÇÃO EM DUAS FORMAS

-- -------
ALTER TABLE ITEM_PRODUTO
MODIFY TIPO_MEDIDA VARCHAR2(30) CONSTRAINT CK_IP_TIPOMEDIDA CHECK(TIPO_MEDIDA IN('LITRO','KILO','UNIDADE'));

ALTER TABLE ITEM_PRODUTO
ADD CONSTRAINT CK_IP_TIPOMEDIDA CHECK(TIPO_MEDIDA IN('LITRO','KILO','UNIDADE'));
-- -------

ALTER TABLE MATERIA_PRIMA
MODIFY MATERIA_PRIMA CONSTRAINT UK_MP_MATERIAPRIMA UNIQUE;

--CONSULTA DOS RELACIONAMENTOS

SELECT * FROM USER_CONSTRAINTS;

--CRIAÇÃO DO SEQUENCE

CREATE SEQUENCE SQC_CATEGORIA;

--ATRIBUIÇÃO DE DADOS DENTRO DA TABELA CATEGORIA

INSERT INTO CATEGORIA
VALUES (SQC_CATEGORIA.NEXTVAL, 'DOCE');

INSERT INTO CATEGORIA
VALUES (SQC_CATEGORIA.NEXTVAL, 'BEBIDA');

INSERT INTO CATEGORIA
VALUES (SQC_CATEGORIA.NEXTVAL, 'CONGELADO');

--CONSULTA DOS DADOS NA TABELA

SELECT * FROM CATEGORIA;
