-- PROJETO AULA 08

-- Arquivo CSV via Kaggle

-- TRANSFORMANDO TODOS OS DADOS TEXTOS EM UPPER CASE

UPDATE
    DESTINY2_GUNS_DATA 
SET 
    GUN_NAME = UPPER(GUN_NAME), 
    GUN_ARCHETYPE = UPPER(GUN_ARCHETYPE), 
    SOURCE_PLACE = UPPER(SOURCE_PLACE),
    ELEMENT_TYPE = UPPER(ELEMENT_TYPE),
    RARITY = UPPER(RARITY),
    WEAPON_TYPE = UPPER(WEAPON_TYPE);

-- SELECT GERAL

SELECT
    * 
FROM
    DESTINY2_GUNS_DATA;

-- CONTAGEM DE RPM ACIMA DE 120 COM ASSOCIAÇÃO ELEMENTAL

SELECT 
    COUNT (ELEMENT_TYPE),
    ELEMENT_TYPE
FROM
    DESTINY2_GUNS_DATA
WHERE
    GUN_ROF > 120
GROUP BY
    ELEMENT_TYPE;

-- CONTAGEM E CONSULTA DE NOME POR TIPO DE ARMA E RARIDADE

SELECT
    COUNT(WEAPON_TYPE)
FROM
    DESTINY2_GUNS_DATA
WHERE
    WEAPON_TYPE = 'FUSION_RIFLE';

SELECT
    GUN_NAME as "FUZIL DE FUSÃO",
    RARITY as RARIDADE
FROM 
    DESTINY2_GUNS_DATA
WHERE 
    WEAPON_TYPE = 'FUSION_RIFLE';

-- CONTAGEM E CONSULTA DE TIPO DE ARMA POR ELEMENTO

SELECT
    COUNT(GUN_NAME),
    WEAPON_TYPE,
    ELEMENT_TYPE
FROM 
    DESTINY2_GUNS_DATA
GROUP BY
    WEAPON_TYPE,
    ELEMENT_TYPE
ORDER BY 
    ELEMENT_TYPE;
    
-- CONTAGEM DE TIPO DE ARMA POR RARIDADE

SELECT
    COUNT(GUN_NAME),
    WEAPON_TYPE,
    RARITY
FROM 
    DESTINY2_GUNS_DATA
GROUP BY
    WEAPON_TYPE,
    RARITY
ORDER BY 
    RARITY;
    
-- LISTAR ARMAS EXÓTICAS

SELECT
    *
FROM
    DESTINY2_GUNS_DATA
WHERE
    RARITY = 'EXOTIC'
ORDER BY
    ELEMENT_TYPE;
    
-- CONTAGEM DE ARMAS POR TIPO ELEMENTAL COM AVG ROF > 120
SELECT
    COUNT(GUN_NAME),
    ELEMENT_TYPE,
    GUN_ARCHETYPE
FROM
    DESTINY2_GUNS_DATA
GROUP BY
    ELEMENT_TYPE,
    GUN_ARCHETYPE
HAVING
    AVG(GUN_ROF) > 120
ORDER BY
    ELEMENT_TYPE;